os: linux
language: python
dist: xenial
jobs:
  include:
    - name: "Minimum NEP 029 versions"
      python: "3.6"
      env: NUMPY_VER=1.16
      script: pytest --cov=pysatModels/
    # Versions with latest numpy
    - name: "3.7 with flake8"
      python: "3.7"
      script: pytest --flake8 --cov=pysatModels/
    - name: "3.8"
      python: "3.8"
      script: pytest --cov=pysatModels/

services: xvfb
addons:
  apt:
    packages:
    - gfortran

install:
  # Use the conda management under the install script, as separate scripts will revert to pip
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  # Once pysat 3.0 is released, remove the custom pysat install and change
  # this to:
  # - while read requirement; do conda install --yes $requirement; done < requirements.txt
  - conda install --yes pandas scipy xarray
  # check for custom version of numpy
  - if [ -z ${NUMPY_VER} ]; then
      echo 'Using latest numpy';
      conda install numpy;
    else
      conda install numpy==$NUMPY_VER;
    fi
  # Install packages not on conda
  - pip install -r test_requirements.txt
  - pip install pyForecastTools
  # Prepare pysat install from git
  - cd ..
  - git clone --single-branch --branch v3-0-rc1 https://github.com/pysat/pysat.git
  - cd pysat
  # Install the pysat requirements
  - while read requirement; do conda install --yes $requirement; done < requirements.txt
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install >/dev/null
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  # install pysatModels
  - cd ../pysatModels
  - python setup.py install

after_success:
  - coveralls --rcfile=setup.cfg
