os: linux
language: python
dist: xenial
jobs:
  include:
    - name: Minimum NEP 029 versions
      python: 3.6
      env: NUMPY_VER=1.16
    # Versions with latest numpy
    - python: 3.6
    - python: 3.7

services: xvfb
addons:
  apt:
    packages:
    - gfortran

install:
  # Use the conda management under the install script, as separate scripts will revert to pip
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas xarray requests beautifulsoup4 lxml netCDF4 nose pytest-cov pytest-ordering future
  - conda activate test-environment
  # check for custom version of numpy
  - if [ -z ${NUMPY_VER} ]; then
      echo 'Using latest numpy';
    else
      conda install numpy==$NUMPY_VER;
    fi
  # Install pysatCDF and dump output
  - pip install pysatCDF >/dev/null
  # Install packages not on conda
  - pip install pytest-flake8
  # conda using old coveralls (1.5.2) which is not working on Travis CI
  - pip install coveralls
  # Prepare pysat install from git
  - cd ..
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - cd ./pysat
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - git checkout develop-3
  - python setup.py install >/dev/null
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  # install pysatModels
  - cd ../pysatModels
  - python setup.py install

script:
  - pytest -vs --cov=pysatModels/  --flake8

after_success:
  - coveralls --rcfile=setup.cfg
